"""Report writer — generates markdown reports from analysis results.

Creates structured markdown reports with analysis summary, key findings,
charts, and statistical results.
"""

import re
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def write_report(
    title: str,
    summary: str,
    findings: list[str] | None = None,
    charts: list[str] | None = None,
    details: str = "",
    model_used: str = "",
) -> Path:
    """Write a markdown report file.

    Args:
        title: Report title.
        summary: Executive summary of the analysis.
        findings: List of key findings (optional).
        charts: List of chart HTML file paths (optional).
        details: Additional analysis details (optional).
        model_used: Model used for analysis (optional).

    Returns:
        Path to the generated report file.
    """
    findings = findings or []
    charts = charts or []

    # Sanitize title for filename
    safe_title = re.sub(r"[^\w\s-]", "", title).strip().lower()
    safe_title = re.sub(r"[\s]+", "-", safe_title)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"{safe_title}-{timestamp}.md"
    output_path = OUTPUT_DIR / filename

    lines = [
        f"# {title}",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]

    if model_used:
        lines.append(f"**Model:** {model_used}",)
        lines.append("")

    lines.extend([
        "## Executive Summary",
        "",
        summary,
        "",
    ])

    if findings:
        lines.extend([
            "## Key Findings",
            "",
        ])
        for i, finding in enumerate(findings, 1):
            lines.append(f"{i}. {finding}")
        lines.append("")

    if charts:
        lines.extend([
            "## Charts",
            "",
        ])
        for chart_path in charts:
            chart_name = Path(chart_path).stem
            lines.append(f"![{chart_name}]({chart_path})")
            lines.append("")

    if details:
        lines.extend([
            "## Detailed Analysis",
            "",
            details,
            "",
        ])

    lines.append("---")
    lines.append("*Report generated by Data Analyst Agent*")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    return output_path
